device: cuda:0
dataset:
  name: MSTAR
  dataset_dir: './datasets/MSTAR/'
  image_size: 128
  n_channels: 3
  n_classes: 10
model:
  type: mstar
  name: resnext
  init_mode: kaiming_fan_out
  resnext:
    depth: 29
    initial_channels: 64
    cardinality: 8
    base_channels: 64
train:
  distributed: False
  dist:
    init_method: env://
    backend: nccl
    node_rank: 0
    world_size: 4
    local_rank: 0

  seed: 4524
  precision: O0
  batch_size: 16
  subdivision: 1
  optimizer: adam
  base_lr: 0.1
  momentum: 0.9
  nesterov: True
  weight_decay: 5e-4
  output_dir: ./experiments/mstar/resnext/exp2-2
  log_period: 100
  checkpoint_period: 100
  val_ratio: 0.0
  use_test_as_val: True
  use_tensorboard: True

  dataloader:
    num_workers: 16
    drop_last: True
    pin_memory: False
validation:
  batch_size: 8
  dataloader:
    num_workers: 1
    drop_last: False
    pin_memory: False
test:
  batch_size: 32
scheduler:
  epochs: 4500
  type: multistep
  milestones: [150, 225]
  lr_decay: 0.1
augmentation:
  use_random_crop: False
  use_random_horizontal_flip: False
  use_cutout: False
  use_random_erasing: False
  use_dual_cutout: False
  use_mixup: False
  use_ricap: False
  use_cutmix: False
  use_label_smoothing: False
  random_crop:
    padding: 4
    fill: 0
    padding_mode: constant
  random_horizontal_flip:
    prob: 0.5
tensorboard:
  train_images: False
  val_images: False
  model_params: False



